name: shogo_app
description: A fully offline application for OCR and matching of shipping tags and product lists.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # --- Core & Utilities ---
  excel: ^4.0.6
  image: ^4.1.7
  intl: ^0.19.0
  path: ^1.9.1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  
  # --- UI & User Input ---
  camera: ^0.11.0+1
  image_picker: ^1.1.2
  file_picker: ^10.3.2 # Excelファイル選択用

  # --- Offline AI & OCR ---
  # Googleのオンデバイス（オフライン）文字認識ライブラリ
  google_mlkit_text_recognition: ^0.15.0
  
  # オンデバイスAIモデルを実行するためのライブラリ（TensorFlow Lite）
  # 将来的に軽量LLMを動かすための基盤
  tflite_flutter: ^0.10.4
  tflite_flutter_helper: ^0.4.4
  
  # --- App Icon Generation ---
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # --- AIモデルや画像アセットをアプリに含める設定 ---
  assets:
    - assets/
    # 将来オンデバイスAIのモデルファイルを置く場所
    - assets/models/ 
    - assets/icon/

  fonts:
   - family: NotoSansJP
     fonts:
       - asset: fonts/NotoSansJP-Regular.ttf
       - asset: fonts/NotoSansJP-Bold.ttf
         weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"