name: shogo_app
description: A fully offline application for OCR and matching of shipping tags and product lists.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # --- Core & Utilities ---
  excel: ^4.0.6
  image: ^4.1.7
  intl: ^0.19.0
  path: ^1.9.1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  
  # --- UI & User Input ---
  camera: ^0.11.0+1
  image_picker: ^1.1.2
  file_picker: ^8.0.0+1

  # --- Offline AI & OCR ---
  google_mlkit_text_recognition: ^0.15.0
  
  # ★★★【変更点】★★★
  # 確実に動作するバージョンの組み合わせに修正しました
  tflite_flutter: ^0.11.0
  
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/models/ 
    - assets/icon/
    - assets/fonts/

  fonts:
   - family: NotoSansJP
     fonts:
       - asset: assets/fonts/NotoSansJP-Regular.ttf
       - asset: assets/fonts/NotoSansJP-Bold.ttf
         weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"